### ISSUE TITLE
Spatial handlers not working

### ISSUE THREAD

**Issue by almereyda** [14mmm/docker-geocouch#1]
When trying to test GeoCouch [as described in its Readme](https://github.com/couchbase/geocouch/tree/couchdb1.3.x#using-geocouch), even with (successfully?) registered spatial handlers as shown by `/_utils/config.html` and correctly built beam files in the `ERL_FLAGS` path, the `bbox` request fails.

```
{"error":"unknown_error","reason":"undef"}

```

Further details can be found in the [process log's gist](https://gist.github.com/almereyda/5cd661c68b52b79c2769).

@andrenarchy, @vmx, @janl, @klaemo: Would you have any specific advice at this point?

Or anyone else who uses CouchDB source builds in a docker container?
@terinjokes @sbisbee @BlackHatMan @rstiller @siegesmund @coastwise @alexindigo @frodenas @mirkokiefer @busbud

**Comment by almereyda** [comment]
Further links from Klaemo's docker-couchdb ecosystem:
- https://github.com/klaemo/docker-couchdb-testing
- https://github.com/klaemo/docker-couchdb-base
- https://github.com/busbud/busbud-couchdb-docker reverse-proxied

---

Some CouchDB Dockerfiles based on source builds for review:
- https://github.com/terinjokes/docker-couchdb
- https://github.com/sbisbee/docker-couchdb
- https://github.com/BlackHatMan/docker-couchdb
- https://github.com/rstiller/docker-couchdb
- https://github.com/siegesmund/couchdb-docker
- https://github.com/coastwise/docker-couchdb
- https://github.com/alexindigo/docker-couchdb
- https://github.com/frodenas/docker-couchdb
- https://github.com/mirkokiefer/dockerfile-couchdb
- https://github.com/mirkokiefer/Dockerfiles/tree/master/couchdb

**Comment by firefrorefiddle** [comment]
I have the same problem. Did you find a solution @almereyda ?

**Comment by almereyda** [comment]
@firefrorefiddle I've recently identified some forks of this repository, but I couldn't test them out yet.
Funny enough we have been talking about this yesterday with @thoka when approaching the next @TransforMap stage.
Should we try working on this together? Unfortunately not even the GeoCouch developer @vmx could help out here.

**Comment by firefrorefiddle** [comment]
@almereyda A colleague gave me the hint about the solution.
In /usr/local/bin/couchdb, replace

`ERL_START_OPTIONS="$ERL_OS_MON_OPTIONS -sasl errlog_type error +K true +A 4"`
with

`ERL_START_OPTIONS="$ERL_OS_MON_OPTIONS -sasl errlog_type error +K true +A 4 -pa 
/opt/geocouch-couchdb1.3.x/ebin"`

and it all works nicely. Perhaps I will make a fork or a pull request for this.

**Comment by almereyda** [comment]
Pull Requests are generally highly appreciated from our side.

**Comment by almereyda** [comment]
@firefrorefiddle I can confirm adding

```
RUN sed -i -e 's/-sasl errlog_type error +K true +A 4/-sasl errlog_type error +K true +A 4 -pa \/opt\/geocouch-couchdb1.3.x\/ebin/g' /usr/local/bin/couchdb
```

to the `# Configuration` part of the Dockerfile helps.

Thank you for providing this feedback, and special thanks to said colleague.

I am closing this issue to prepare for a refork of @klaemo's CouchDB image due to https://github.com/docker-library/official-images/pull/1288#issuecomment-178902163
